// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SchoolLynxLibrary.Models
{
    public partial class Classgroup
    {
        public Classgroup()
        {
            Messages = new HashSet<Message>();
            People = new HashSet<Person>();
        }

        public int Id { get; set; }
        public string Groupname { get; set; } = null!;

        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}