// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SchoolLynxLibrary.Models
{
    public partial class Confirmation
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int MessageId { get; set; }
        public DateTime ConfirmedOn { get; set; }

        [JsonIgnore]
        public virtual Message Message { get; set; } = null!;

        public virtual Person Person { get; set; } = null!;
    }
}