// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SchoolLynxLibrary.Models
{
    public partial class Message
    {
        public Message()
        {
            Confirmations = new HashSet<Confirmation>();
        }

        public int Id { get; set; }
        public string? Title { get; set; }
        public string Text { get; set; } = null!;
        public int SenderId { get; set; }
        public int ClassgroupId { get; set; }
        public DateTime? SentOn { get; set; }

        public virtual Classgroup? Classgroup { get; set; } = null;
        public virtual Person? Sender { get; set; } = null;
        public virtual ICollection<Confirmation>? Confirmations { get; set; }
    }
}